### ISSUE TITLE
Fix the borders to be dashed

### ISSUE THREAD

**Issue by pythagoraswitch** [wbg-bigdata/nightlights#27]
See #19 for the dashed borders. 
+ the border between Jammu & Kashmir and Himachal Pradesh
+ the border between China's disputed territory and Arunachal Pradesh/Assam
are not dashed yet. 

This should be priority over other fixes as we opened up the website for beta.

**Comment by anandthakker** [comment]
This should now be fixed:

<img width="508" alt="screen shot 2016-02-06 at 5 39 58 pm" src="https://cloud.githubusercontent.com/assets/4974151/12869844/cad6af20-ccf8-11e5-900a-482ab26eed70.png">

<img width="522" alt="screen shot 2016-02-06 at 5 39 15 pm" src="https://cloud.githubusercontent.com/assets/4974151/12869845/ccdac270-ccf8-11e5-9601-e610b4080d30.png">

**Comment by anandthakker** [comment]
(left hand side is before, right hand side is after/current)

**Comment by pythagoraswitch** [comment]
Looks great! Thank you!
